### PR TITLE
added emotions table

### PR DESCRIPTION
**Pull request by snelson44**
I added a table for the emotions data and followed the checklist in the readme. All tests passing.

### CODE REVIEW

**Comment by Scottamattic** [comment]
Gorgeous! Is this on the Ubuntu server?

Loving the actual code development tooling we got going on here.

**Comment by palash-t** [comment]
Beautiful, dude!

**Review by palash-t — APPROVED** [review]
Quick question: had a question about the input args to insert_emotion()
Like the data is neutral, anger, happiness, surprise, sadness represented as %s
What do these input args mean? Are the emotion people inputting these values as integers (on a scale of 1-10) for each emotion?

**Comment by snelson44** [comment]
I'm thinking they will be inputting decimals that represent percents, like 0.3 or 0.4, meaning 30% and 40% respectively. The %s isn't typical printf formatting, I don't think it carries or expects a certain type. So I would say the emotion team is inputting these as floats on a scale of 0.0 to 0.99.

**Pull request merged**
